### ISSUE TITLE
[feat] Implementation of a footer for OpenlySource

### ISSUE THREAD

**Issue by hparashar27** [hparashar27/OpenlySource#15]

**Comment by nikhilsnayak3473** [comment]
I can work upon this feature. Please assign me to this issue and provide some more details of the contents to be included in FOOTER

**Comment by hparashar27** [comment]
Make a basic footer with some mandatory details as all website have like 
Company name and logo
With Gmail, Instagram, linkdin, Twitter,gitHub logo
All header items  

You can take help from this -
https://www.google.com/search?q=footer+example&client=ms-android-xiaomi-rev1&prmd=ivn&sxsrf=AJOqlzViynoxUsDN6naXGFH3ON857i89MA:1674624219117&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiVnNmt_eH8AhXsTWwGHYwBBgEQ_AUoAXoECAIQAQ&biw=393&bih=764&dpr=2.75#imgrc=BxZxxZWU6qkI7M

**Comment by nikhilsnayak3473** [comment]
can you assign me to this issue

**Comment by nikhilsnayak3473** [comment]
Is there any more improvements i can do with respect to footer?

**Comment by hparashar27** [comment]
for now its ok , later we can improve it
