### ISSUE TITLE
Implementation of About us page 

### ISSUE THREAD

**Issue by hparashar27** [hparashar27/OpenlySource#16]
the about us page is all about the description and detailed information of the openlysource community , where you get answers forall such question like 
What is Openlysource , why i should join it or how it helped me , What is the aim of openlysource 
so , start building it ...
and for more help , reach out to our community on slack - openlysource.slack.com

**Comment by lokeshvasnik** [comment]
add me to this community

**Comment by hparashar27** [comment]
@lokeshvasnik  join with this link -> 
https://lnkd.in/dvVB7Cfk

**Comment by lokeshvasnik** [comment]
Great
