### ISSUE TITLE
Make Member page responsive

### ISSUE THREAD

**Issue by hparashar27** [hparashar27/OpenlySource#28]

**Comment by lokeshvasnik** [comment]
Assign me this task

**Comment by hparashar27** [comment]
So, @lokeshvasnik the member page looks like 

There is a main heading at the top ->
Want to become Openlysource member ? 
then there is form , the form contains -
Profile pic
Name
Github profile
Share your thought about Open-source 

then there is list of our members in the form of testimonials  like this 
![reviews](https://user-images.githubusercontent.com/96375055/216065483-c8995e9f-e404-40d2-a6f8-5189677a7714.jpg)

**Comment by lokeshvasnik** [comment]
On it!

**Comment by lokeshvasnik** [comment]
Where is the form?

**Comment by hparashar27** [comment]
There is a button in center just below the main heading which will redirect the user to the form ,  make one page for form as well so when user clicks on the button it redirect to the form so it is like 

The main heading first " Want to become openlysource member ? 
Then their is button named " join us " below this heading which redirect user to form page .The form also contain submit button as well

Then the list of testimonials

I hope you got it

**Comment by thevinitgupta** [comment]
I would love to contribute if the issue is still open.

**Comment by hparashar27** [comment]
I assigned this issue to @lokeshvasnik already . So you can work on issue #49 if you want

**Comment by thevinitgupta** [comment]
He unassigned it that's why I asked I could contribute.

**Comment by lokeshvasnik** [comment]
Feel free to work on the member page brother as I already completed it you can go for responsiveness if there is anything left

**Comment by hparashar27** [comment]
@lokeshvasnik are you still working on the member form for this member page?

**Comment by lokeshvasnik** [comment]
> @lokeshvasnik are you still working on the member form for this member page? 

No

**Comment by hparashar27** [comment]
okay then @thevinitgupta you can start working on this issue , all the things has been done only the member form left so for now you just make a member form take a look at this type of form - 

https://user-images.githubusercontent.com/96375055/220121816-4aa893c6-50bb-4d92-ae74-02aa5e10c211.mp4

**Comment by thevinitgupta** [comment]
the page already seems to be responsive.
@lokeshvasnik can you specify what you wanted to be done?

**Comment by hparashar27** [comment]
@thevinitgupta yes you are right the member page is almost responsive , you can make about us page responsive

**Comment by lokeshvasnik** [comment]
Yes @thevinitgupta it's already responsive and I completed the page already long back that's the reason I unassigned the task and wanted to close the issue
