### ISSUE TITLE
Create DeleteEvent and UpdateEvent APIs

### ISSUE THREAD

**Issue by hparashar27** [hparashar27/OpenlySource#30]

**Comment by hparashar27** [comment]
@Faizan-omer  you can start working on this 👍

**Comment by Samim104** [comment]
hello sir, I want to work in open source. I have good experience in NodeJS. can you please assign me this issue?

**Comment by hparashar27** [comment]
@Samim104 yes you can but on these APIs he is already working  , but soon other backend issues are on their way , check it out later . You can star this repo to get upcoming updates 👍

**Comment by Samim104** [comment]
@hparashar27 ok thank you

**Comment by hparashar27** [comment]
@Samim104 would you like to work on this issue ?

**Comment by Samim104** [comment]
@hparashar27  yes i want to

**Comment by Samim104** [comment]
@hparashar27 please review the pr

**Comment by Samim104** [comment]
bro add me in slack. 
email : samimsk7017@gmail.com
