### ISSUE TITLE
Add darkTheme to the opportunities page 

### ISSUE THREAD

**Issue by hparashar27** [hparashar27/OpenlySource#40]

**Comment by MonalikaPatnaik** [comment]
Hey...I would like to work on this issue!

**Comment by hparashar27** [comment]
@MonalikaPatnaik  you can but currently i am working on it  almost completed , you can start working on the " curated guide to open source " page  👍

**Comment by MonalikaPatnaik** [comment]
sure!

**Comment by hparashar27** [comment]
completed
