### ISSUE TITLE
Create post and get Apis for members page

### ISSUE THREAD

**Issue by hparashar27** [hparashar27/OpenlySource#43]
https://user-images.githubusercontent.com/96375055/217533988-481bcea6-15c9-4578-9142-478592cb1c26.mp4

so the apis containing these fields -
*name
*image-
upload image
remove image 
change image
in order to upload images configure multer  
*github profile link 
*thought

so these apis work like in this way , when a user fills up the member form -
in which he set his/her name , upload profile pic , github profile link and his/her thought on open source
on submitting the form the post request  trigger and get request is used to render that data of members in form of testimonials

**Comment by hparashar27** [comment]
@Faizan-omer or @Samim104  who wants to work on this amazing issue

**Comment by Samim104** [comment]
assign me

**Comment by Samim104** [comment]
@hparashar27  I don't think it's a good idea to store images in mongo. I think we should store image url in db only.

**Comment by hparashar27** [comment]
@Samim104  then how user can remove , change and upload image from his/her local system ?

**Comment by Samim104** [comment]
@hparashar27  i think you can use firebase to store images

**Comment by hparashar27** [comment]
Hmm... Okay you do one thing for now left the image field in Apis . We can think about it later

**Comment by alokVerma749** [comment]
I worked on this issue, and now members are getting saved with form data into the db on route `http://localhost:8000/api/members`(works well on postman)
But on browser 'OpenlySource' is getting attached to the route 
## ScreeeanShot
![image](https://user-images.githubusercontent.com/87599400/221348553-fa9bde92-f4f3-4ccd-8dab-6b0a4be3728f.png)
as you can see in **requeest url**
> Have you any idea about from where it is coming from
