### ISSUE TITLE
[feat] create APIs for signup and login 

### ISSUE THREAD

**Issue by hparashar27** [hparashar27/OpenlySource#47]

**Comment by thevinitgupta** [comment]
I would love to work on this

**Comment by TechLateef** [comment]
I will love to work on this

**Comment by hparashar27** [comment]
thanks @thevinitgupta @TechLateef for willing to work, as of now these apis are not necessary for our application so let wait for some there backend issues or you can check other issues ?

**Comment by thevinitgupta** [comment]
Sure, thanks @hparashar27
