### ISSUE TITLE
make opportunities page responsive

### ISSUE THREAD

**Issue by hparashar27** [hparashar27/OpenlySource#48]

**Comment by lokeshvasnik** [comment]
Assign this task to me

**Comment by hparashar27** [comment]
@lokeshvasnik are you working on this issue

**Comment by hparashar27** [comment]
@lokeshvasnik are you still working on this issue ?

**Comment by lokeshvasnik** [comment]
> @lokeshvasnik are you still working on this issue ?
> 

No

**Comment by munnokd** [comment]
Hello @hparashar27 can you assign this issue to me?
