### ISSUE TITLE
Upadtion of README.md File

### ISSUE THREAD

**Issue by hparashar27** [hparashar27/OpenlySource#5]
try to improve the readme.md file of OpenlySource

**Comment by safil-badarudeen** [comment]
hey brother , In my opinion we should add more detail into it  , like how a exactly a beginner can contribute , we should explain every detail even the steps one should follow in local system while trying to contribute, let me know your opinion

**Comment by hparashar27** [comment]
yes that would be great , i am assigning it to you Make changes according to you .Best of luck

**Comment by lokeshvasnik** [comment]
Hello, I would like to ask one question I want to make the navbar look good and contribute more to it should I use tailwind CSS??

**Comment by safil-badarudeen** [comment]
tail wind css is way better, normal css it is 3X more time consuming than tailwind css and with  less attractive finishing

**Comment by hparashar27** [comment]
@lokeshvasnik  ok you can use tailwind css and made changes according to you in navbar . before submitting PR, upload one screenshot of navbar 👍
