### ISSUE TITLE
Module not found: Error: Can't resolve 'reactstrap' in ./src/Components/Members/Member.js

### ISSUE THREAD

**Issue by PKM777** [hparashar27/OpenlySource#55]
Found this issue in Member.js file

**Comment by dlipahir** [comment]
Hello @PKM777 
I would like to work on this issue. kindly assign me!
Thanks!

**Comment by hparashar27** [comment]
this issue can be solved by - " npm install reactstrap ". Or do you have any other approach @dlipahir

**Comment by alokVerma749** [comment]
actually `reactstrap` is not listed as a dependency in `package.json`
