### ISSUE TITLE
Making About us page responsive 

### ISSUE THREAD

**Issue by hparashar27** [hparashar27/OpenlySource#57]

**Comment by Yasir761** [comment]
I would like to work on this.

**Comment by Gautam-10137** [comment]
I would also like to work on this.

**Comment by hparashar27** [comment]
@Yasir761 are you still working on this issue?

**Comment by Saikat-Mandal** [comment]
@Yasir761 are you still working on it ?

**Comment by AbhishekBhamare** [comment]
@hparashar27 Can I take this issue?

**Comment by hparashar27** [comment]
@Saikat-Mandal  would you like to work on this issue ?

**Comment by Saikat-Mandal** [comment]
@hparashar27 yeh sure !

**Comment by hparashar27** [comment]
@AbhishekBhamare you can this issue

**Comment by Saikat-Mandal** [comment]
@hparashar27 should i use taiwind css or just normal css only ?

**Comment by hparashar27** [comment]
you have done it greatly, would you like to work on the issue #48
