### ISSUE TITLE
Add signup and login button in Navbar

### ISSUE THREAD

**Issue by hparashar27** [hparashar27/OpenlySource#6]
Add Signup or login button in Navbar after github navbar item

**Comment by ria28** [comment]
I can try doing this. Can you assign it to me?

**Comment by hparashar27** [comment]
@ria28  yes you can try

**Comment by ria28** [comment]
Would you like me to route the user to the under construction/ coming soon page for now?

**Comment by hparashar27** [comment]
yes now can route the user to coming soon page , but later when the backend is going to ready then it will work like real authentication

**Comment by GrandsonOfRachappa** [comment]
yeh i can do that

**Comment by hparashar27** [comment]
@GrandsonOfRachappa its done brother , you can raise some other issues
