### ISSUE TITLE
[bug] not able to connect to MongoDB database 

### ISSUE THREAD

**Issue by hparashar27** [hparashar27/OpenlySource#69]
@Faizan-omer 
 Brother can you check out this issue, the issue is about the connection with the database which you have implemented with 
 your MongoDB database.

can you give me access to your this app database 

 
![Code_kKbtnkAU4C](https://user-images.githubusercontent.com/96375055/222475448-436b9f0f-7f72-4a96-bb1c-2840118a0413.png)

**Comment by Saikat-Mandal** [comment]
hey @hparashar27 I just ran it locally but everything seems fine to me
![OpenlySource - Visual Studio Code 06-03-2023 09_52_33](https://user-images.githubusercontent.com/75900118/223019041-80d91dd5-360d-4f3d-b9e0-ad676cf7af40.png)
