### ISSUE TITLE
[feat] Improve resource guide page 

### ISSUE THREAD

**Issue by hparashar27** [hparashar27/OpenlySource#70]
This feature is about how to get started with open source contribution , this feature is basically a single page where you guide how to start with open source

**Comment by 8rxn** [comment]
### Hi @hparashar27 , 
I would Like to work on this feature.

**Comment by hparashar27** [comment]
@8rxn yes you can start working on it

**Comment by 8rxn** [comment]
> @8rxn Actually @MonalikaPatnaik has recently added this feature in the about us page as "resources", So you can go through the resources guide page and try to work on its responsiveness, add some more features, and bugs fix if any

Okay I'll work on it...
