### ISSUE TITLE
[feat] Design Signup/Login form page 

### ISSUE THREAD

**Issue by hparashar27** [hparashar27/OpenlySource#8]
OpenlySource requires a better Design Suggestion for Login and Signup page , I am not going to assign this to anyone please share your design as s screenshot . The best will be selected

**Comment by SumeetMaurya** [comment]
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/95906826/213908655-a881f923-14ac-4069-8184-91bade80e918.png">
This is from my personal project

**Comment by SumeetMaurya** [comment]
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/95906826/213908708-2fbfa57c-3b03-4e1d-9944-0b2c01fcf72d.png">
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/95906826/213908725-904d25cd-a431-4c71-8434-df6f8185c077.png">

These are from my personal project

**Comment by lokeshvasnik** [comment]
![Homepage](https://user-images.githubusercontent.com/91425128/213911322-97de7143-b494-4c90-9eb4-611d4eac4d40.png)

Check this out

**Comment by hparashar27** [comment]
great designs , but i think the right place to share your design is on slack community so that other contributors have their own opinion 
openlysource.slack.com

**Comment by hparashar27** [comment]
@SumeetMaurya brother i want you to do little changes to your design regarding color and to the ui 
in place of dark-gray color use this color - #040C18
in place of green-bluish color use this color - #002853
and in place of the mobile-boy-sitting ui use some eath-networking type ui of #040C18 color then it will best 
i want these changes because the header of openlysource is made these two color , I hope you got it

If you want any help then please ask me on - openlysource.slack.com

**Comment by SumeetMaurya** [comment]
Okay I'll try out the changes and show you the results as soon as I can

**Comment by SumeetMaurya** [comment]
@hparashar27 please provide the gradient for the login button as well

**Comment by hparashar27** [comment]
yes sure , you can find it in src>app.css>.gradient_bg

**Comment by hparashar27** [comment]
@SumeetMaurya  any update ?

**Comment by SumeetMaurya** [comment]
https://user-images.githubusercontent.com/95906826/214303530-b8a3fd92-d739-4301-9956-81bc73daa1be.mp4

hey @hparashar27 sorry for late reply , This is all the changes you said were required

**Comment by SumeetMaurya** [comment]
let me know if anything else needs to be changed

**Comment by hparashar27** [comment]
It's too good brother 😍👍

**Comment by hparashar27** [comment]
@SumeetMaurya bro can you implement it in react ?

**Comment by SumeetMaurya** [comment]
yeah I can do it

**Comment by hparashar27** [comment]
Great! , So you can start working on it 
Means when user click on login it shows login page and when user click on signup button then it will show sign up page ..
 All the best , waiting for your PR ☺️

**Comment by SumeetMaurya** [comment]
@hparashar27 so my goal is to only work on frontend and I don't have to work on the backend, so I don't have set up the values in the sign up and login page right?

**Comment by hparashar27** [comment]
Now you only make it in frontend , later on we can work on its backend

**Comment by SumeetMaurya** [comment]
okay then I'll start my work

**Comment by hparashar27** [comment]
@SumeetMaurya you are doing great , i mean this is new project and it requires someone like you and me , who can scale it up to big ... If you contribute regularly to this repo . Then we surely make it large

You can join this slack channel as well 
OpenlySource.slack.com

**Comment by SumeetMaurya** [comment]
yeah for sure, I'll try my best

**Comment by SumeetMaurya** [comment]
I'm unable to join the slack channel, I don't know how to use it
<img width="705" alt="image" src="https://user-images.githubusercontent.com/95906826/214370567-b925bbf9-42da-495a-bf38-4bca9f6dd707.png">

**Comment by hparashar27** [comment]
Give me your email id , i will add you

**Comment by SumeetMaurya** [comment]
sumeetmaurya135@gmail.com

**Comment by SumeetMaurya** [comment]
hey @hparashar27 please review the code and proceed it further, and the javascript is not working which is supposed to add animation to the text writer, in Login.jsx and Signup.jsx , for now can we just merge this code to create the pages, and later on maybe I can resolve this issue, I'm new to react so I don't know what's wrong, but I'll figure it out soon.
