### ISSUE TITLE
Fixing Overlapping issue in Opportunities section

### ISSUE THREAD

**Issue by webgaurav02** [hparashar27/OpenlySource#85]
I would like to fix the overlapping of Visit button in Opportunities page in Desktop and smaller viewports

**To Reproduce**
1. Go to Opportunities
2. Scroll down to "Reinforcement Learning Open Source Fest"
5. See error

**Screenshots**
![OpenlySourceIssue](https://github.com/hparashar27/OpenlySource/assets/115694968/e1935526-91e2-4cbd-b849-c5287f4c91a8)

**Comment by hparashar27** [comment]
@webgaurav02  you can start working on this issue
